// This file is released under the 3-clause BSD license. See COPYING-BSD.
// Generated by builder.sce: Please, do not edit this file.
// ------------------------------------------------------
curdir = pwd();
scriptdir = get_file_path('loader.sce');
chdir(scriptdir);
// ------------------------------------------------------
jarFilePath = fullfile(scriptdir, '..\..\jar\com.bytecode_asia.jar');
javaclasspath(fullpath(jarFilePath));
// ------------------------------------------------------
chdir(curdir);
clear curdir;
